config/routes.rb
Rails.application.routes.draw do

  root 'organizations#index'

  devise_for :users, path: '', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
  }

  post '/search', to: 'home#search'

  get '/saved_contents', to: 'home#saved'

  resources :organizations do

    post '/invit', to: 'organizations#send_invit'
    get '/join', to: 'organizations#join'

    delete '/assignment/:assignment_id', to: 'organizations#delete_assignment', as: :delete_assignment

    resources :tags

    resources :contents do
      post '/to_read', to: 'contents#to_read'
      post '/like', to: 'contents#like'
    end
  end

end

app/views/shared/_add_content.html.erb
<% if @organization.try(:id) %>
    <div id="add-content-button">
      <a href="<%= new_organization_content_path(@organization) %>">
        <i class="material-icons">add</i>
      </a>
    </div>
<% end %>

app/views/shared/_content.html.erb
<% if content %>
    <div id="content_<%= content.id %>" class="grid-item">
      <a class="content-header-link" href="<%= organization_content_path(content.organization, content) %>">
        <div class="content-header" style="background-image: url('<%= content.try(:image_url).try(:html_safe) %>');background-position: center center;background-repeat: no-repeat;background-size:cover;">
          <%= content_tag :span, content.try(:title), class: 'content-title' %>
          <%= content_tag :span, t(:'content.created_by', name: "#{content.user.firstname} #{content.user.lastname}"), class: 'content-author' %>
        </div>
      </a>
      <% if can? :update, content %>
          <a class="content-edit" href="<%= edit_organization_content_path(content.organization, content) %>"><i class="material-icons">create</i></a>
      <% end %>
      <div class="content-description">
        <%= content_tag :p, content.try(:description).try(:html_safe) %>
      </div>
      <div class="content-importance">
        <%= content_tag :span, t(:"content.importance.#{content.importance}") %>
      </div>
      <div class="content-tags">
        <% content.tags.each do |t| %>
            <%= content_tag :span, t.name, class: 'tag' %>
        <% end %>
      </div>
      <div class="content-actions">
        <span class="message-left">
          <% if @organization %>

          <% else %>
              <%= t('from', f: content.organization.name) %>
          <% end %>
        </span>
        <ul>
          <li>
            <a href="<%= organization_content_like_path(content.organization, content) %>" class="like <%= 'active' if ContentsSaved.is_liked?(content, current_user) %>" data-remote="true" data-method="post">
              <i class="material-icons"><%= ContentsSaved.is_liked?(content, current_user) ? 'favorite' : 'favorite_border' %></i>
            </a>
          </li>
          <li>
            <a href="<%= organization_content_to_read_path(content.organization, content) %>" class="to_read <%= 'active' if ContentsSaved.is_saved_to_read?(content, current_user) %>" data-remote="true" data-method="post">
              <i class="material-icons">access_time</i>
            </a>
          </li>
        </ul>
      </div>
    </div>
<% end %>

app/views/shared/_contents.html.erb
<div class="grid">

  <% if contents.blank? %>
    <%= image_tag :smileybad, class: 'no-contents' %>
  <% else %>
      <% contents.each do |c| %>
          <%= render partial: 'shared/content', locals: {content: c} %>
      <% end %>
  <% end %>
</div>

app/views/shared/_header.html.erb
<header class="navbar">
  <div class="nav navbar-header">
    <%= link_to image_tag(:logo), root_path, class: 'navbar-brand' %>
  </div>

  <ul class="nav navbar-left">
    <% if user_signed_in? %>

    <% end %>
  </ul>


  <%= form_tag search_path(), method: :post, class: 'nav navbar-form' do %>
      <div class="form-group">
        <%= text_field_tag :q, @search_keywords, placeholder: t(:search), class: 'form-control' %>
        <i class="material-icons">search</i>
      </div>
  <% end %>


  <ul class="nav navbar-right">
    <li>
      <a href="<%= saved_contents_path %>">
        <i class="material-icons">access_time</i> <%= t('saved_to_read') %>
      </a>
    </li>
    <% if user_signed_in? %>
        <%= content_tag :li, (link_to t(:sign_out), destroy_user_session_path, method: :delete) %></li>
    <% else %>

    <% end %>
  </ul>

</header>

app/views/shared/_notifications.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success">
      <i type="button" class="material-icons">close</i>
      <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-danger">
      <i class="material-icons">close</i>
      <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_organizations_bar.html.erb
<% if user_signed_in? %>

    <div id="sidebar" class="col-sm-3 col-md-2 hidden-xs sidebar">
      <ul>
        <% current_user.organizations.each do |o| %>
            <li>
              <div class="title">
                <%= link_to o.name, organization_path(o), class: 'title' %>
                <% if can? :update, o %>
                    <a href="<%= edit_organization_path(o) %>" class="edit"><i class="material-icons">create</i></a>
                <% end %>
              </div>
              <ul>
                <% o.tags.each do |t| %>
                    <li>
                      <%= link_to t.name, organization_tag_path(o, t), class: 'tag' %>
                    </li>
                <% end %>
              </ul>
            </li>
        <% end %>
      </ul>

      <div class="add-organization col-sm-3 col-md-2 hidden-xs">
        <%= link_to '+', new_organization_path %>
      </div>
    </div>

<% end %>

app/views/shared/_sidebar.html.erb
<% if user_signed_in? %>

    <div id="sidebar" class="col-sm-3 col-md-2 hidden-xs sidebar">
      <ul>
        <% Organization.by_assignments(current_user).each do |o| %>
            <li>
              <div class="title <%= 'active' if o == @organization %>">
                <%= link_to o.name, organization_path(o), class: 'title' %>
                <% if can? :update, o %>
                    <a href="<%= edit_organization_path(o) %>" class="edit"><i class="material-icons">create</i></a>
                <% end %>
              </div>
              <ul>
                <% o.tags.each do |t| %>
                    <li>
                      <% classes = ['tag'] %>
                      <% classes << 'active' if t == @tag %>
                      <%= link_to t.name, organization_tag_path(o, t), class: classes %>
                    </li>
                <% end %>
              </ul>
            </li>
        <% end %>
      </ul>

      <div class="add-organization col-sm-3 col-md-2 hidden-xs">
        <a href="<%= new_organization_path %>">
          <i class="material-icons">add</i>
        </a>
      </div>
    </div>

<% end %>

app/views/shared/_single_content.html.erb
<% if content %>
  <div id="content_<%= content.id %>">
    <a href="<%= organization_content_path(content.organization, content) %>">
      <%= content.title %>
    </a>
  </div>
<% end %>