config/routes.rb
Rails.application.routes.draw do

  root 'organizations#index'

  devise_for :users, path: '', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
  }

  post '/search', to: 'home#search'

  get '/saved_contents', to: 'home#saved'

  resources :organizations do

    post '/invit', to: 'organizations#send_invit'
    get '/join', to: 'organizations#join'

    delete '/assignment/:assignment_id', to: 'organizations#delete_assignment', as: :delete_assignment

    resources :tags

    resources :contents do
      post '/to_read', to: 'contents#to_read'
      post '/like', to: 'contents#like'
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord

  belongs_to :organization

  has_and_belongs_to_many :contents

  scope :by_organization, -> (organization) {
    where(organization: organization)
  }

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  load_and_authorize_resource :organization, find_by: :slug
  load_and_authorize_resource :tag, through: :organization

  # GET /tags
  # GET /tags.json
  def index
    redirect_to organization_path(@organization)
    #@tags = Tag.by_organization(@organization)
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)
    @tag.organization = @organization

    respond_to do |format|
      if @tag.save
        format.html { redirect_to edit_organization_path(@organization), notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { redirect_to edit_organization_path(@organization) }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to [@organization, @tag], notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to edit_organization_path(@organization), notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for ([@organization,tag]) do |f| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, placeholder: t('placeholder.new_tag.name') %>
    <%= f.submit (tag.new_record? ? t(:tag_new_submit) : t(:tag_edit_submit)), class: 'after-input' %>
  </div>

<% end %>

app/views/tags/edit.html.erb
<% content_for :header do %>
    <%= render partial: 'shared/header', locals: {current: :tags} %>
<% end %>

<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', organization_tag_path(@organization,@tag) %> |
<%= link_to 'Back', organization_tags_path %>

app/views/tags/index.html.erb
<% content_for :header do %>
    <%= render partial: 'shared/header', locals: {current: :tags} %>
<% end %>
<h1>Tags</h1>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', organization_tag_path(@organization, tag) %></td>
        <% if can? :manage, tag %>
            <td><%= link_to 'Edit', edit_organization_tag_path(@organization, tag) %></td>
            <td><%= link_to 'Destroy', organization_tag_path(@organization, tag), method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_organization_tag_path if can? :create, @organization.tags.build %>

app/views/tags/new.html.erb
<% content_for :header do %>
    <%= render partial: 'shared/header', locals: {current: :tags} %>
<% end %>

<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', organization_tags_path %>

app/views/tags/show.html.erb
<% content_for :header do %>
    <%= render partial: 'shared/header', locals: {current: :tags} %>
<% end %>

<h2 class="title-uppercase"><%= "#{@organization.name} > #{@tag.name}" %></h2>

<%= render partial: 'shared/contents', locals: {contents: @tag.contents} %>