config/routes.rb
Rails.application.routes.draw do

  root 'organizations#index'

  devise_for :users, path: '', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
  }

  post '/search', to: 'home#search'

  get '/saved_contents', to: 'home#saved'

  resources :organizations do

    post '/invit', to: 'organizations#send_invit'
    get '/join', to: 'organizations#join'

    delete '/assignment/:assignment_id', to: 'organizations#delete_assignment', as: :delete_assignment

    resources :tags

    resources :contents do
      post '/to_read', to: 'contents#to_read'
      post '/like', to: 'contents#like'
    end
  end

end

app/models/organization.rb
class Organization < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :tags
  accepts_nested_attributes_for :tags

  has_many :assignments
  has_many :users, through: :assignments

  has_many :contents

  scope :by_assignments, -> (current_user) {
    joins(:assignments).where(assignments: {user_id: current_user.id, is_active: true})
  }

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  load_and_authorize_resource :organization, find_by: :slug

  before_action :set_organization, only: [:invit, :send_invit, :delete_assignment]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.by_assignments(current_user)
    @contents = Content.accessible(current_user)
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)
    @organization.assignments << Assignment.new({user: current_user, organization: @organization, is_admin: true, is_active: true})

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_invit
    if user = User.find_by_email(params[:email])
      if user.organizations.include? @organization
        flash[:notice] = t(:'organization.user_already_invited')
        render :edit
      else
        user.new_token!
        assignment = Assignment.new(organization: @organization, user: user, is_active: false, is_admin: false)
        assignment.save!
        assignment.new_token!
        OrganizationMailer.send_invit(assignment).deliver_now
        flash[:notice] = t(:'organization.invit_email_sent')
        render :edit
      end
    else
      flash[:alert] = t(:'organization.invit_user_not_found')
      render :edit
    end
  end

  def join
    if assignment = Assignment.find_by(assignment_token: params[:assignment_token])
      assignment.activate!
      redirect_to organization_path(assignment.organization), notice: "You succefully joined #{assignment.organization.name}"
    else
      redirect_to organizations_path, alert: 'Error'
    end
  end

  def delete_assignment
    Assignment.find(params[:assignment_id]).destroy
    redirect_to edit_organization_path(@organization), notice: 'User was successfully removed from this group.'
  end

  private
  def set_organization
    @organization = Organization.find_by_slug(params[:organization_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def organization_params
    params.require(:organization).permit(:name)
  end

end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(organization) do |f| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t('organzation.label.name'), class: '' %>
    <%= f.text_field :name, placeholder: t('placeholder.new_organization.name') %>
  </div>

  <div class="form-group">
    <%= f.submit (@organization.new_record? ? t(:organization_new_submit) : t(:organization_edit_submit)), class: 'btn btn-raised btn-primary' %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<% content_for :header do %>
    <%= render partial: 'shared/header', locals: {current: :organizations} %>
<% end %>

<h2 class="title-uppercase">Editing Organization</h2>

<%= render 'form', organization: @organization %>

<h3>Editing tags</h3>

<div class="list">
  <% @organization.tags.each do |t| %>
      <span class="organization-tag tag">
        <%= t.name %>
        <%= link_to content_tag(:i,'close',class:'material-icons'), organization_tag_path(@organization, t), method: :delete, data: {confirm: 'Are you sure?'} %>
      </span>
  <% end %>
</div>

<%= render 'tags/form', tag: Tag.new %>

<h3>Editing Users</h3>

<div class="list">
  <% @organization.assignments.each do |a| %>
      <span class="organization-user tag">
        <%= "#{a.user.firstname} #{a.user.lastname}" %>
        <%= link_to content_tag(:i,'close', class:'material-icons after-input'), organization_delete_assignment_path(@organization, a), method: :delete, data: {confirm: 'Are you sure?'} unless a.user == current_user %>
      </span>
  <% end %>
</div>

<%= form_tag organization_invit_path(@organization), method: :post do %>
    <div class="form-group">
      <%= email_field_tag :email, '', placeholder: t('placeholder.add_user.email') %>
      <%= submit_tag t('organization.add_user.submit'), class: 'after-input' %>
    </div>

<% end %>

app/views/organizations/index.html.erb
<% content_for :header do %>
    <%= render partial: 'shared/header', locals: {current: :organizations} %>
<% end %>

<h1 class="title-uppercase"><%= t('content_from_anywhere') %></h1>

<%= render partial: 'shared/contents', locals: {contents: @contents} %>

app/views/organizations/new.html.erb
<% content_for :header do %>
    <%= render partial: 'shared/header', locals: {current: :organizations} %>
<% end %>

<h1 class="title-uppercase">New Organization</h1>

<%= render 'form', organization: @organization %>

app/views/organizations/show.html.erb
<% content_for :header do %>
    <%= render partial: 'shared/header', locals: {current: :organizations} %>
<% end %>

<h1 class="title-uppercase"><%= @organization.name %></h1>

<%= render partial: 'shared/contents', locals: {contents: @organization.contents} %>